# Generated by Django 6.0.3 on 2026-04-07 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=100)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('situação', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserTaks',
        ),
    ]
