# Generated by Django 6.0.4 on 2026-04-09 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=100)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Andamento'), ('C', 'Concluída')], max_length=1)),
                ('prazo', models.CharField(default='', max_length=100)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='pessoas.pessoa')),
            ],
        ),
    ]
