# Generated by Django 6.0.3 on 2026-03-25 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(default='', max_length=100)),
                ('descricao', models.CharField(default='', max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('data', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
